# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true


# Git Branch
[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 4
truncation_symbol = ''

# Git Commit
[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '

#Git State
[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

# Git Metrics
[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '


# Git Status
[git_status]
conflicted = 'ğŸ³ âš”ï¸'
#up_to_date = 'âœ“'
untracked = 'ğŸ¤”${count}'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = 'ğŸ—ƒï¸ [++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘ Ã— ${count}'

ahead = 'â‡¡${count}'
behind = 'â‡£${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
